#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SGEA_Call.Resource", IsApplication=true)]

namespace SGEA_Call
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int centerToLeft = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int centerToRight = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int leftToCenter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int rightToCenter = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int menuItem = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int branco = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int fundo = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int topo = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int vermelho = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int botao = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circuloFone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int circuloTel = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icone500PX = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconeCalendario = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int retangulo = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0024
			public const int botaoCalendario = 2131361828;
			
			// aapt resource value: 0x7f0a000d
			public const int botaoCel = 2131361805;
			
			// aapt resource value: 0x7f0a0021
			public const int botaoEntrar = 2131361825;
			
			// aapt resource value: 0x7f0a000c
			public const int botaoFixo = 2131361804;
			
			// aapt resource value: 0x7f0a0023
			public const int botaoMenu = 2131361827;
			
			// aapt resource value: 0x7f0a001a
			public const int botaoOK = 2131361818;
			
			// aapt resource value: 0x7f0a005e
			public const int botaoVisitaA = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int botaoVisitaP = 2131361887;
			
			// aapt resource value: 0x7f0a0007
			public const int campoBairro = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int campoCNPJ = 2131361808;
			
			// aapt resource value: 0x7f0a0006
			public const int campoCep = 2131361798;
			
			// aapt resource value: 0x7f0a006c
			public const int campoConfirmado = 2131361900;
			
			// aapt resource value: 0x7f0a0064
			public const int campoDesc = 2131361892;
			
			// aapt resource value: 0x7f0a0005
			public const int campoEmail = 2131361797;
			
			// aapt resource value: 0x7f0a001f
			public const int campoLogin = 2131361823;
			
			// aapt resource value: 0x7f0a0065
			public const int campoMedidas = 2131361893;
			
			// aapt resource value: 0x7f0a0003
			public const int campoNome = 2131361795;
			
			// aapt resource value: 0x7f0a006e
			public const int campoObs = 2131361902;
			
			// aapt resource value: 0x7f0a0068
			public const int campoPrecoT = 2131361896;
			
			// aapt resource value: 0x7f0a0067
			public const int campoPrecoU = 2131361895;
			
			// aapt resource value: 0x7f0a0066
			public const int campoQuant = 2131361894;
			
			// aapt resource value: 0x7f0a0011
			public const int campoRS = 2131361809;
			
			// aapt resource value: 0x7f0a0008
			public const int campoRua = 2131361800;
			
			// aapt resource value: 0x7f0a0020
			public const int campoSenha = 2131361824;
			
			// aapt resource value: 0x7f0a0004
			public const int campoSexo = 2131361796;
			
			// aapt resource value: 0x7f0a0063
			public const int campoTipo = 2131361891;
			
			// aapt resource value: 0x7f0a006b
			public const int campoValidade = 2131361899;
			
			// aapt resource value: 0x7f0a000b
			public const int centerPoint = 2131361803;
			
			// aapt resource value: 0x7f0a005b
			public const int cliente = 2131361883;
			
			// aapt resource value: 0x7f0a002e
			public const int d1 = 2131361838;
			
			// aapt resource value: 0x7f0a0037
			public const int d10 = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int d11 = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int d12 = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int d13 = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int d14 = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int d15 = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int d16 = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int d17 = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int d18 = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int d19 = 2131361856;
			
			// aapt resource value: 0x7f0a002f
			public const int d2 = 2131361839;
			
			// aapt resource value: 0x7f0a0041
			public const int d20 = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int d21 = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int d22 = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int d23 = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int d24 = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int d25 = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int d26 = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int d27 = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int d28 = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int d29 = 2131361866;
			
			// aapt resource value: 0x7f0a0030
			public const int d3 = 2131361840;
			
			// aapt resource value: 0x7f0a004b
			public const int d30 = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int d31 = 2131361868;
			
			// aapt resource value: 0x7f0a0031
			public const int d4 = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int d5 = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int d6 = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int d7 = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int d8 = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int d9 = 2131361846;
			
			// aapt resource value: 0x7f0a0054
			public const int data = 2131361876;
			
			// aapt resource value: 0x7f0a0059
			public const int descricao = 2131361881;
			
			// aapt resource value: 0x7f0a0052
			public const int detalhesVisita = 2131361874;
			
			// aapt resource value: 0x7f0a0071
			public const int forn = 2131361905;
			
			// aapt resource value: 0x7f0a0026
			public const int grid = 2131361830;
			
			// aapt resource value: 0x7f0a0055
			public const int horario = 2131361877;
			
			// aapt resource value: 0x7f0a0001
			public const int imageView1 = 2131361793;
			
			// aapt resource value: 0x7f0a001e
			public const int imageView2 = 2131361822;
			
			// aapt resource value: 0x7f0a0062
			public const int imagem = 2131361890;
			
			// aapt resource value: 0x7f0a006f
			public const int jMenu = 2131361903;
			
			// aapt resource value: 0x7f0a0022
			public const int labelMensagem = 2131361826;
			
			// aapt resource value: 0x7f0a001b
			public const int list_header_title = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int list_item_title = 2131361820;
			
			// aapt resource value: 0x7f0a0019
			public const int listaAno = 2131361817;
			
			// aapt resource value: 0x7f0a0016
			public const int listaMes = 2131361814;
			
			// aapt resource value: 0x7f0a0057
			public const int local = 2131361879;
			
			// aapt resource value: 0x7f0a0069
			public const int menuProdutos = 2131361897;
			
			// aapt resource value: 0x7f0a006a
			public const int menuServicos = 2131361898;
			
			// aapt resource value: 0x7f0a0025
			public const int mes = 2131361829;
			
			// aapt resource value: 0x7f0a004d
			public const int p1 = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int p2 = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int p3 = 2131361871;
			
			// aapt resource value: 0x7f0a0050
			public const int p4 = 2131361872;
			
			// aapt resource value: 0x7f0a0060
			public const int quant = 2131361888;
			
			// aapt resource value: 0x7f0a001d
			public const int relativeLayout1 = 2131361821;
			
			// aapt resource value: 0x7f0a0070
			public const int relatorio = 2131361904;
			
			// aapt resource value: 0x7f0a0061
			public const int root = 2131361889;
			
			// aapt resource value: 0x7f0a0027
			public const int s1 = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int s2 = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int s3 = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int s4 = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int s5 = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int s6 = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int s7 = 2131361837;
			
			// aapt resource value: 0x7f0a0051
			public const int scroll1 = 2131361873;
			
			// aapt resource value: 0x7f0a0013
			public const int tableLayout1 = 2131361811;
			
			// aapt resource value: 0x7f0a0053
			public const int tableLayout2 = 2131361875;
			
			// aapt resource value: 0x7f0a0014
			public const int tableRow1 = 2131361812;
			
			// aapt resource value: 0x7f0a0017
			public const int tableRow2 = 2131361815;
			
			// aapt resource value: 0x7f0a000a
			public const int telCel = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int telFixo = 2131361801;
			
			// aapt resource value: 0x7f0a000e
			public const int textView = 2131361806;
			
			// aapt resource value: 0x7f0a0002
			public const int textView1 = 2131361794;
			
			// aapt resource value: 0x7f0a0015
			public const int textView2 = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int textView3 = 2131361816;
			
			// aapt resource value: 0x7f0a0056
			public const int textView4 = 2131361878;
			
			// aapt resource value: 0x7f0a0058
			public const int textView5 = 2131361880;
			
			// aapt resource value: 0x7f0a005a
			public const int textView6 = 2131361882;
			
			// aapt resource value: 0x7f0a005c
			public const int textView7 = 2131361884;
			
			// aapt resource value: 0x7f0a005d
			public const int textView8 = 2131361885;
			
			// aapt resource value: 0x7f0a0012
			public const int textoPerfis = 2131361810;
			
			// aapt resource value: 0x7f0a000f
			public const int textoVisitas = 2131361807;
			
			// aapt resource value: 0x7f0a0000
			public const int toolbar1 = 2131361792;
			
			// aapt resource value: 0x7f0a006d
			public const int verCliente = 2131361901;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cliente = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DadosCliente = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DadosFornecedor = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Data = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fornecedor = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Orcamento = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Produtos = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Relatorio = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SelecaoOrcamento = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Servicos = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int JMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int menu = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Botao = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int MyTheme = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int telCel = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int telFixo = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int title = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int titleBar = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
